spring.application.name=bibliopelis
# Puerto del servidor (opcional)
server.port=8080
# Configuracion de la base de datos PostgreSQL, no pponer los datos reales en Github
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliopelis
spring.datasource.username=bibliopelis-app
spring.datasource.password=bibliopelis
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log del Hikari (Pool de conexiones)
# Con este atributo en modo DEBUG da informacion del POOL
logging.level.com.zaxxer.hikari=DEBUG
# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5